# How to use config.ts file instead on yaml and start supporting types in the project
# https://github.com/settings/developers
# https://docs.netlify.com/security/secure-access-to-sites/oauth-provider-tokens/#netlify-ui-settings
backend:
  name: github
  repo: beonefront/qonnectone-www
  branch: main
  auth_scope: repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
